### ISSUE TITLE
Array/Struct constructors

### ISSUE THREAD

**Issue by RemyCiterin** [Copilot-Language/copilot#458] opened 2023-09-22 12:44 UTC
I discovered Copilot a little while ago and I've been trying to do some metaprogramming/abstractions to manipulate streams (for example to do matrix computation...), one solution I thought of was to use Array or Struct of streams to represent matrices for example. But there are destructors from `Stream (Array n a)` to `Array n (Stream a)` like using `(.!!)` but I haven't found any constructors for passing from `Array n (Stream a)` to `Stream (Array n a)` (same for structs), so to do matrix multiplication, I can destroy the matrix in a float stream to do the operations `(+)`, `(-)`, `(*)`... term to term but I can't reconstruct the result. 
Is there a way of doing this that I haven't seen?

**Comment by ivanperez-keera** [comment] 2023-09-25 05:36
This is duplicate of #36 .

The short answer is it's on the way. Recently, @InnovativeInventor extended Copilot to be able to update an array with new values, which makes it possible to construct an array from the parts. I can put that in a branch so that you can use it, just know that it's not Copilot-official yet and it may change.

In theory, we could leverage the same ideas to update a struct, but I have not tried it and I cannot determine how much effort will be needed to make that work.

Irrespective of that, we've also discussed the possibility of adding vector operations to Copilot to produce C code that takes advantage of whatever the existing CPU/GPU on the system may offer (e.g., CUDA). This is a longer-term discussion; if we can get an intern to work on this, then maybe we can incorporate it.

I'm closing this in favor of #36, feel free to comment there.

**Closed by ivanperez-keera** 2023-09-25 05:36 UTC
